export const API_URL = "https://localhost:7078"; // Base URL for the client
export const INFRASTRUCTURE_URL = "/api/infrastructure" as const;
export const ENUM_TRANSLATIONS_URL = "/api/infrastructure/enums/{enumName}" as const;
export const LOGIN_URL = "/api/Users/Login" as const;
export const MACZKOPAT_PARCELS_URL = "/api/Parcels/Maczkopat/{maczkopatId}" as const;
export const MACZKOPATS_URL = "/api/maczkopats" as const;
export const MACZKOPAT_BY_ID_URL = "/api/maczkopats/{maczkopatId}" as const;
export const ROUTE_STREAM_URL = "/api/routes/geojson-stream/{routeId}" as const;
export const ROUTE_URL = "/api/routes" as const;
export const ROUTE_BY_COURIER_URL = "/api/routes/{courierId}" as const;
export const ROUTE_CALCULATE_URL = "/api/routes/calculate/{routeId}" as const;
export const ROUTE_SAVE_CALCULATION_URL = "/api/routes/save-calculation" as const;
export const PARCEL_TRACK_URL = "/api/Parcels/{parcelFriendlyId}/track" as const;
export const PARCEL_LOGS_URL = "/api/Parcels" as const;
export const PARCEL_UPDATE_URL = "/api/Parcels/Update" as const;
export const POST_METHOD = "post" as const;
export const GET_METHOD = "get" as const;