export const API_URL = "http://localhost:5188"; // Base URL for the client
export const INFRASTRUCTURE_URL = "/api/infrastructure" as const;
export const LOGIN_URL = "/api/Users/Login" as const;
export const MACZKOPAT_PARCELS_URL = "/api/Parcels/Maczkopat/{maczkopatId}" as const;
export const ROUTE_STREAM_URL = "/api/routes/geojson-stream/{routeId}" as const;
export const ROUTE_URL = "/api/routes"
export const PARCEL_LOGS_URL = "/api/Parcels" as const;
export const PARCEL_UPDATE_URL = "/api/Parcels/Update" as const;
export const POST_METHOD = "post" as const;
export const GET_METHOD = "get" as const;