CREATE TABLE "Addresses" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Alias" text NOT NULL,
    "City" text NOT NULL,
    "PostalCode" text NOT NULL,
    "Street" text NOT NULL,
    "CountryCode" text NOT NULL,
    "BuildingNumber" integer NOT NULL,
    "Location" geometry NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id")
);

CREATE TABLE "Areas" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AreaName" text NOT NULL,
    CONSTRAINT "PK_Areas" PRIMARY KEY ("Id")
);

CREATE TABLE "StaticEnums" (
    "EnumName" text NOT NULL,
    CONSTRAINT "PK_StaticEnums" PRIMARY KEY ("EnumName")
);

CREATE TABLE "UserRoles" (
    "Id" uuid NOT NULL,
    "RoleName" integer NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "StaticEnumTranslations" (
    "EnumValue" integer NOT NULL,
    "EnumName" text NOT NULL,
    "TranslationLanguage" text NOT NULL,
    "Translation" text NOT NULL,
    "EnumEntityEnumName" text,
    "StaticEnumEntityEnumName" text NOT NULL,
    CONSTRAINT "PK_StaticEnumTranslations" PRIMARY KEY ("EnumValue", "EnumName", "TranslationLanguage"),
    CONSTRAINT "FK_StaticEnumTranslations_StaticEnums_EnumEntityEnumName" FOREIGN KEY ("EnumEntityEnumName") REFERENCES "StaticEnums" ("EnumName"),
    CONSTRAINT "FK_StaticEnumTranslations_StaticEnums_StaticEnumEntityEnumName" FOREIGN KEY ("StaticEnumEntityEnumName") REFERENCES "StaticEnums" ("EnumName") ON DELETE CASCADE
);

CREATE TABLE "UsersInternal" (
    "Id" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    "UserName" text,
    "Email" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "PhoneNumber" text,
    CONSTRAINT "PK_UsersInternal" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UsersInternal_UserRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "UserRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Maczkopats" (
    "Id" uuid NOT NULL,
    "Code" text NOT NULL,
    "AreaId" bigint NOT NULL,
    "AddressId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    CONSTRAINT "PK_Maczkopats" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Maczkopats_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Maczkopats_Areas_AreaId" FOREIGN KEY ("AreaId") REFERENCES "Areas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Maczkopats_UsersInternal_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UsersInternal" ("Id")
);

CREATE TABLE "Routes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "StartAddressId" bigint NOT NULL,
    "EndAddressId" bigint NOT NULL,
    "Distace" bigint NOT NULL,
    "Locations" geometry[] NOT NULL,
    "CreatedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    CONSTRAINT "PK_Routes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Routes_UsersInternal_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UsersInternal" ("Id")
);

CREATE TABLE "UsersExternal" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "PhoneNumber" text NOT NULL,
    "Email" text NOT NULL,
    "InternalUserId" uuid,
    "UserInternalId" uuid,
    CONSTRAINT "PK_UsersExternal" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UsersExternal_UsersInternal_UserInternalId" FOREIGN KEY ("UserInternalId") REFERENCES "UsersInternal" ("Id")
);

CREATE TABLE "MaczkopatEventLogs" (
    "Id" uuid NOT NULL,
    "EventLogType" integer NOT NULL,
    "LogMessage" text,
    "MaczkopatId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    CONSTRAINT "PK_MaczkopatEventLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MaczkopatEventLogs_Maczkopats_MaczkopatId" FOREIGN KEY ("MaczkopatId") REFERENCES "Maczkopats" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MaczkopatEventLogs_UsersInternal_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UsersInternal" ("Id")
);

CREATE TABLE "Vehicles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Capacity" integer NOT NULL,
    "DistanceRidden" bigint NOT NULL,
    "RouteEntityId" bigint,
    "CreatedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    CONSTRAINT "PK_Vehicles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Vehicles_Routes_RouteEntityId" FOREIGN KEY ("RouteEntityId") REFERENCES "Routes" ("Id"),
    CONSTRAINT "FK_Vehicles_UsersInternal_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UsersInternal" ("Id")
);

CREATE TABLE "Parcels" (
    "Id" uuid NOT NULL,
    "FriendlyId" text NOT NULL,
    "Product" text NOT NULL,
    "FromUserExternalId" uuid,
    "ReceiverUserExternalId" uuid,
    "MaczkopatEntityId" uuid NOT NULL,
    "UserExternalId" uuid,
    "CreatedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    CONSTRAINT "PK_Parcels" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Parcels_Maczkopats_MaczkopatEntityId" FOREIGN KEY ("MaczkopatEntityId") REFERENCES "Maczkopats" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Parcels_UsersExternal_UserExternalId" FOREIGN KEY ("UserExternalId") REFERENCES "UsersExternal" ("Id"),
    CONSTRAINT "FK_Parcels_UsersInternal_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UsersInternal" ("Id")
);

CREATE TABLE "NumberTemplates" (
    "Id" uuid NOT NULL,
    "TemplateNumber" text NOT NULL,
    "VehicleEntityId" bigint,
    "CreatedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    CONSTRAINT "PK_NumberTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_NumberTemplates_UsersInternal_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UsersInternal" ("Id"),
    CONSTRAINT "FK_NumberTemplates_Vehicles_VehicleEntityId" FOREIGN KEY ("VehicleEntityId") REFERENCES "Vehicles" ("Id")
);

CREATE TABLE "CommunicationEventLogs" (
    "Id" uuid NOT NULL,
    "Sender" text,
    "Receiver" text,
    "Message" text NOT NULL,
    "ParcelId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    CONSTRAINT "PK_CommunicationEventLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CommunicationEventLogs_Parcels_ParcelId" FOREIGN KEY ("ParcelId") REFERENCES "Parcels" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CommunicationEventLogs_UsersInternal_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UsersInternal" ("Id")
);

CREATE TABLE "ParcelEventLogs" (
    "Id" uuid NOT NULL,
    "Message" text NOT NULL,
    "ParcelEventLogType" integer NOT NULL,
    "ParcelId" uuid NOT NULL,
    "CreatedAt" timestamp with time zone,
    "UpdatedAt" timestamp with time zone,
    "CreatedById" uuid,
    CONSTRAINT "PK_ParcelEventLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ParcelEventLogs_Parcels_ParcelId" FOREIGN KEY ("ParcelId") REFERENCES "Parcels" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ParcelEventLogs_UsersInternal_CreatedById" FOREIGN KEY ("CreatedById") REFERENCES "UsersInternal" ("Id")
);

CREATE INDEX "IX_CommunicationEventLogs_CreatedById" ON "CommunicationEventLogs" ("CreatedById");

CREATE INDEX "IX_CommunicationEventLogs_ParcelId" ON "CommunicationEventLogs" ("ParcelId");

CREATE INDEX "IX_MaczkopatEventLogs_CreatedById" ON "MaczkopatEventLogs" ("CreatedById");

CREATE INDEX "IX_MaczkopatEventLogs_MaczkopatId" ON "MaczkopatEventLogs" ("MaczkopatId");

CREATE INDEX "IX_Maczkopats_AddressId" ON "Maczkopats" ("AddressId");

CREATE INDEX "IX_Maczkopats_AreaId" ON "Maczkopats" ("AreaId");

CREATE INDEX "IX_Maczkopats_CreatedById" ON "Maczkopats" ("CreatedById");

CREATE INDEX "IX_NumberTemplates_CreatedById" ON "NumberTemplates" ("CreatedById");

CREATE INDEX "IX_NumberTemplates_VehicleEntityId" ON "NumberTemplates" ("VehicleEntityId");

CREATE INDEX "IX_ParcelEventLogs_CreatedById" ON "ParcelEventLogs" ("CreatedById");

CREATE INDEX "IX_ParcelEventLogs_ParcelId" ON "ParcelEventLogs" ("ParcelId");

CREATE INDEX "IX_Parcels_CreatedById" ON "Parcels" ("CreatedById");

CREATE INDEX "IX_Parcels_MaczkopatEntityId" ON "Parcels" ("MaczkopatEntityId");

CREATE INDEX "IX_Parcels_UserExternalId" ON "Parcels" ("UserExternalId");

CREATE INDEX "IX_Routes_CreatedById" ON "Routes" ("CreatedById");

CREATE INDEX "IX_StaticEnumTranslations_EnumEntityEnumName" ON "StaticEnumTranslations" ("EnumEntityEnumName");

CREATE INDEX "IX_StaticEnumTranslations_StaticEnumEntityEnumName" ON "StaticEnumTranslations" ("StaticEnumEntityEnumName");

CREATE INDEX "IX_UsersExternal_UserInternalId" ON "UsersExternal" ("UserInternalId");

CREATE INDEX "IX_UsersInternal_RoleId" ON "UsersInternal" ("RoleId");

CREATE INDEX "IX_Vehicles_CreatedById" ON "Vehicles" ("CreatedById");

CREATE INDEX "IX_Vehicles_RouteEntityId" ON "Vehicles" ("RouteEntityId");