// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OutpostImmobile.Persistence;

#nullable disable

namespace OutpostImmobile.Persistence.Migrations
{
    [DbContext(typeof(OutpostImmobileDbContext))]
    [Migration("20251228194656_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgrouting");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.AddressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.AreaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Logs.CommunicationEventLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<string>("Receiver")
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParcelId");

                    b.ToTable("CommunicationEventLogs");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Logs.MaczkopatEventLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("EventLogType")
                        .HasColumnType("integer");

                    b.Property<Guid>("MaczkopatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MaczkopatId");

                    b.ToTable("MaczkopatEventLogs");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Logs.ParcelEventLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParcelEventLogType")
                        .HasColumnType("integer");

                    b.Property<Guid>("ParcelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParcelId");

                    b.ToTable("ParcelEventLogs");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.MaczkopatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("AreaId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Maczkopats");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.NumberTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("TemplateNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("VehicleEntityId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("VehicleEntityId");

                    b.ToTable("NumberTemplates");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.ParcelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("FriendlyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FromUserExternalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaczkopatEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ReceiverUserExternalId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserExternalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MaczkopatEntityId");

                    b.HasIndex("UserExternalId");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.RouteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<long>("Distace")
                        .HasColumnType("bigint");

                    b.Property<long>("EndAddressId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<Point[]>("Locations")
                        .IsRequired()
                        .HasColumnType("geometry[]");

                    b.Property<long>("StartAddressId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.StaticEnums.StaticEnumEntity", b =>
                {
                    b.Property<string>("EnumName")
                        .HasColumnType("text");

                    b.HasKey("EnumName");

                    b.ToTable("StaticEnums");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.StaticEnums.StaticEnumTranslationEntity", b =>
                {
                    b.Property<int>("EnumValue")
                        .HasColumnType("integer");

                    b.Property<string>("EnumName")
                        .HasColumnType("text");

                    b.Property<string>("TranslationLanguage")
                        .HasColumnType("text");

                    b.Property<string>("EnumEntityEnumName")
                        .HasColumnType("text");

                    b.Property<string>("StaticEnumEntityEnumName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EnumValue", "EnumName", "TranslationLanguage");

                    b.HasIndex("EnumEntityEnumName");

                    b.HasIndex("StaticEnumEntityEnumName");

                    b.ToTable("StaticEnumTranslations");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Users.UserExternal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InternalUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserInternalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserInternalId");

                    b.ToTable("UsersExternal");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Users.UserInternal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<long?>("RouteId")
                        .HasColumnType("bigint");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RouteId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.VehicleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<long>("DistanceRidden")
                        .HasColumnType("bigint");

                    b.Property<long?>("RouteEntityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("RouteEntityId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Logs.CommunicationEventLogEntity", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OutpostImmobile.Persistence.Domain.ParcelEntity", "Parcel")
                        .WithMany("CommunicationEventLogs")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Logs.MaczkopatEventLogEntity", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OutpostImmobile.Persistence.Domain.MaczkopatEntity", "Maczkopat")
                        .WithMany("MaczkopatEventLogs")
                        .HasForeignKey("MaczkopatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Maczkopat");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Logs.ParcelEventLogEntity", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OutpostImmobile.Persistence.Domain.ParcelEntity", "Parcel")
                        .WithMany("ParcelEventLogs")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.MaczkopatEntity", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutpostImmobile.Persistence.Domain.AreaEntity", "Area")
                        .WithMany("Maczkopats")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("Address");

                    b.Navigation("Area");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.NumberTemplateEntity", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OutpostImmobile.Persistence.Domain.VehicleEntity", null)
                        .WithMany("NumberTemplateEntities")
                        .HasForeignKey("VehicleEntityId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.ParcelEntity", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OutpostImmobile.Persistence.Domain.MaczkopatEntity", "Maczkopat")
                        .WithMany("Parcels")
                        .HasForeignKey("MaczkopatEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserExternal", null)
                        .WithMany("Parcels")
                        .HasForeignKey("UserExternalId");

                    b.Navigation("CreatedBy");

                    b.Navigation("Maczkopat");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.RouteEntity", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.StaticEnums.StaticEnumTranslationEntity", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.StaticEnums.StaticEnumEntity", "EnumEntity")
                        .WithMany()
                        .HasForeignKey("EnumEntityEnumName");

                    b.HasOne("OutpostImmobile.Persistence.Domain.StaticEnums.StaticEnumEntity", null)
                        .WithMany("Translations")
                        .HasForeignKey("StaticEnumEntityEnumName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnumEntity");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Users.UserExternal", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", "UserInternal")
                        .WithMany()
                        .HasForeignKey("UserInternalId");

                    b.Navigation("UserInternal");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Users.UserInternal", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.RouteEntity", "Route")
                        .WithMany("Couriers")
                        .HasForeignKey("RouteId");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.VehicleEntity", b =>
                {
                    b.HasOne("OutpostImmobile.Persistence.Domain.Users.UserInternal", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("OutpostImmobile.Persistence.Domain.RouteEntity", null)
                        .WithMany("AssignedVehicles")
                        .HasForeignKey("RouteEntityId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.AreaEntity", b =>
                {
                    b.Navigation("Maczkopats");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.MaczkopatEntity", b =>
                {
                    b.Navigation("MaczkopatEventLogs");

                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.ParcelEntity", b =>
                {
                    b.Navigation("CommunicationEventLogs");

                    b.Navigation("ParcelEventLogs");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.RouteEntity", b =>
                {
                    b.Navigation("AssignedVehicles");

                    b.Navigation("Couriers");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.StaticEnums.StaticEnumEntity", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.Users.UserExternal", b =>
                {
                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("OutpostImmobile.Persistence.Domain.VehicleEntity", b =>
                {
                    b.Navigation("NumberTemplateEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
