import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../schema";
import {API_URL} from "../Consts.ts"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
    baseUrl: API_URL,
});
export const $api = createClient(fetchClient);