import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../schema";
import {API_URL} from "../Consts.ts"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
    baseUrl: API_URL,
});

fetchClient.use({
    onRequest({ request }) {
        const token = localStorage.getItem("token");
        if (token) {
            request.headers.set("Authorization", `Bearer ${token}`);
        }
        return request;
    },
});

export const $api = createClient(fetchClient);